# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\Administrator\Desktop\processdlg.ui'
#
# Created by: PyQt5 UI code generator 5.9
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_processDlg(object):
    def setupUi(self, processDlg):
        processDlg.setObjectName("processDlg")
        processDlg.resize(619, 361)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(processDlg)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.stackedWidget = QtWidgets.QStackedWidget(processDlg)
        self.stackedWidget.setObjectName("stackedWidget")
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.page)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_files = QtWidgets.QLabel(self.page)
        self.label_files.setObjectName("label_files")
        self.verticalLayout.addWidget(self.label_files)
        self.listWidget_files = QtWidgets.QListWidget(self.page)
        self.listWidget_files.setObjectName("listWidget_files")
        item = QtWidgets.QListWidgetItem()
        self.listWidget_files.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget_files.addItem(item)
        self.verticalLayout.addWidget(self.listWidget_files)
        self.verticalLayout_3.addLayout(self.verticalLayout)
        self.stackedWidget.addWidget(self.page)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.page_2)
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_print = QtWidgets.QLabel(self.page_2)
        self.label_print.setObjectName("label_print")
        self.verticalLayout_2.addWidget(self.label_print)
        self.graphicsView_print = QtWidgets.QGraphicsView(self.page_2)
        self.graphicsView_print.setObjectName("graphicsView_print")
        self.verticalLayout_2.addWidget(self.graphicsView_print)
        self.verticalLayout_6.addLayout(self.verticalLayout_2)
        self.stackedWidget.addWidget(self.page_2)
        self.verticalLayout_4.addWidget(self.stackedWidget)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButton_setting = QtWidgets.QPushButton(processDlg)
        self.pushButton_setting.setObjectName("pushButton_setting")
        self.horizontalLayout.addWidget(self.pushButton_setting)
        self.pushButton_printdlg = QtWidgets.QPushButton(processDlg)
        self.pushButton_printdlg.setObjectName("pushButton_printdlg")
        self.horizontalLayout.addWidget(self.pushButton_printdlg)
        self.pushButton_quickview = QtWidgets.QPushButton(processDlg)
        self.pushButton_quickview.setObjectName("pushButton_quickview")
        self.horizontalLayout.addWidget(self.pushButton_quickview)
        self.pushButton_next = QtWidgets.QPushButton(processDlg)
        self.pushButton_next.setObjectName("pushButton_next")
        self.horizontalLayout.addWidget(self.pushButton_next)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.pushButton_print = QtWidgets.QPushButton(processDlg)
        self.pushButton_print.setObjectName("pushButton_print")
        self.horizontalLayout.addWidget(self.pushButton_print)
        self.pushButton_printall = QtWidgets.QPushButton(processDlg)
        self.pushButton_printall.setObjectName("pushButton_printall")
        self.horizontalLayout.addWidget(self.pushButton_printall)
        self.pushButton_sendmail = QtWidgets.QPushButton(processDlg)
        self.pushButton_sendmail.setObjectName("pushButton_sendmail")
        self.horizontalLayout.addWidget(self.pushButton_sendmail)
        self.verticalLayout_4.addLayout(self.horizontalLayout)
        self.verticalLayout_5.addLayout(self.verticalLayout_4)
        self.label_files.setBuddy(self.listWidget_files)
        self.label_print.setBuddy(self.graphicsView_print)

        self.retranslateUi(processDlg)
        self.stackedWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(processDlg)
        processDlg.setTabOrder(self.listWidget_files, self.pushButton_setting)
        processDlg.setTabOrder(self.pushButton_setting, self.pushButton_printdlg)
        processDlg.setTabOrder(self.pushButton_printdlg, self.pushButton_quickview)
        processDlg.setTabOrder(self.pushButton_quickview, self.pushButton_print)
        processDlg.setTabOrder(self.pushButton_print, self.pushButton_sendmail)
        processDlg.setTabOrder(self.pushButton_sendmail, self.graphicsView_print)

    def retranslateUi(self, processDlg):
        _translate = QtCore.QCoreApplication.translate
        processDlg.setWindowTitle(_translate("processDlg", "数据处理进程"))
        self.label_files.setText(_translate("processDlg", "文件处理队列"))
        __sortingEnabled = self.listWidget_files.isSortingEnabled()
        self.listWidget_files.setSortingEnabled(False)
        item = self.listWidget_files.item(0)
        item.setText(_translate("processDlg", "2017年12月6日"))
        item = self.listWidget_files.item(1)
        item.setText(_translate("processDlg", "2017年12月5日"))
        self.listWidget_files.setSortingEnabled(__sortingEnabled)
        self.label_print.setText(_translate("processDlg", "打印预览"))
        self.pushButton_setting.setText(_translate("processDlg", "设置(&S)"))
        self.pushButton_printdlg.setText(_translate("processDlg", "自定义打印(&C)"))
        self.pushButton_quickview.setText(_translate("processDlg", "预览(&V)"))
        self.pushButton_next.setText(_translate("processDlg", "预览下一页(&N)"))
        self.pushButton_print.setText(_translate("processDlg", "打印(&P)"))
        self.pushButton_printall.setText(_translate("processDlg", "打印全部(&A)"))
        self.pushButton_sendmail.setText(_translate("processDlg", "批量写入数据库并发送邮件(&W)"))

