# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\Corkine\Documents\工作文件夹\[APP]Login2\main.ui'
#
# Created by: PyQt5 UI code generator 5.9
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(443, 650)
        self.verticalLayout = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout.setObjectName("verticalLayout")
        spacerItem = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout.addItem(spacerItem)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.radioButton_school = QtWidgets.QRadioButton(Dialog)
        self.radioButton_school.setToolTip("")
        self.radioButton_school.setToolTipDuration(-1)
        self.radioButton_school.setWhatsThis("")
        self.radioButton_school.setObjectName("radioButton_school")
        self.horizontalLayout.addWidget(self.radioButton_school)
        self.radioButton_wlan = QtWidgets.QRadioButton(Dialog)
        self.radioButton_wlan.setObjectName("radioButton_wlan")
        self.horizontalLayout.addWidget(self.radioButton_wlan)
        self.radioButton_ct = QtWidgets.QRadioButton(Dialog)
        self.radioButton_ct.setObjectName("radioButton_ct")
        self.horizontalLayout.addWidget(self.radioButton_ct)
        self.radioButton_cmcc = QtWidgets.QRadioButton(Dialog)
        self.radioButton_cmcc.setObjectName("radioButton_cmcc")
        self.horizontalLayout.addWidget(self.radioButton_cmcc)
        self.radioButton_cu = QtWidgets.QRadioButton(Dialog)
        self.radioButton_cu.setObjectName("radioButton_cu")
        self.horizontalLayout.addWidget(self.radioButton_cu)
        self.gridLayout.addLayout(self.horizontalLayout, 5, 1, 1, 1)
        self.label_user = QtWidgets.QLabel(Dialog)
        self.label_user.setObjectName("label_user")
        self.gridLayout.addWidget(self.label_user, 2, 0, 1, 1, QtCore.Qt.AlignLeft)
        self.label_logo = QtWidgets.QLabel(Dialog)
        font = QtGui.QFont()
        font.setFamily("百度综艺简体")
        font.setPointSize(14)
        self.label_logo.setFont(font)
        self.label_logo.setObjectName("label_logo")
        self.gridLayout.addWidget(self.label_logo, 0, 0, 1, 3)
        self.lineEdit_user = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_user.setObjectName("lineEdit_user")
        self.gridLayout.addWidget(self.lineEdit_user, 2, 1, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem1, 2, 3, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem2, 6, 1, 1, 1)
        self.label_passwd = QtWidgets.QLabel(Dialog)
        self.label_passwd.setObjectName("label_passwd")
        self.gridLayout.addWidget(self.label_passwd, 3, 0, 1, 1, QtCore.Qt.AlignLeft)
        self.lineEdit_passwd = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_passwd.setAcceptDrops(False)
        self.lineEdit_passwd.setInputMethodHints(QtCore.Qt.ImhNone)
        self.lineEdit_passwd.setClearButtonEnabled(False)
        self.lineEdit_passwd.setObjectName("lineEdit_passwd")
        self.gridLayout.addWidget(self.lineEdit_passwd, 3, 1, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem3, 2, 2, 1, 1)
        spacerItem4 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem4, 1, 0, 1, 1)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem5, 7, 3, 1, 1)
        self.stackedWidget = QtWidgets.QStackedWidget(Dialog)
        self.stackedWidget.setObjectName("stackedWidget")
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.page_2)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setContentsMargins(50, -1, -1, -1)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem6)
        self.verticalLayout_3.addLayout(self.horizontalLayout_4)
        self.checkBox_keeppasswd = QtWidgets.QCheckBox(self.page_2)
        self.checkBox_keeppasswd.setObjectName("checkBox_keeppasswd")
        self.verticalLayout_3.addWidget(self.checkBox_keeppasswd)
        self.checkBox_auth = QtWidgets.QCheckBox(self.page_2)
        self.checkBox_auth.setObjectName("checkBox_auth")
        self.verticalLayout_3.addWidget(self.checkBox_auth)
        self.checkBox_server = QtWidgets.QCheckBox(self.page_2)
        self.checkBox_server.setObjectName("checkBox_server")
        self.verticalLayout_3.addWidget(self.checkBox_server)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.verticalLayout_3.addLayout(self.horizontalLayout_6)
        spacerItem7 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem7)
        self.pushButton_test = QtWidgets.QPushButton(self.page_2)
        self.pushButton_test.setCheckable(False)
        self.pushButton_test.setDefault(False)
        self.pushButton_test.setFlat(False)
        self.pushButton_test.setObjectName("pushButton_test")
        self.verticalLayout_3.addWidget(self.pushButton_test)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.pushButton_lanlogin = QtWidgets.QPushButton(self.page_2)
        self.pushButton_lanlogin.setCheckable(True)
        self.pushButton_lanlogin.setObjectName("pushButton_lanlogin")
        self.horizontalLayout_5.addWidget(self.pushButton_lanlogin)
        self.pushButton_lanlogout = QtWidgets.QPushButton(self.page_2)
        self.pushButton_lanlogout.setObjectName("pushButton_lanlogout")
        self.horizontalLayout_5.addWidget(self.pushButton_lanlogout)
        self.verticalLayout_3.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.pushButton_wlanlogin = QtWidgets.QPushButton(self.page_2)
        self.pushButton_wlanlogin.setCheckable(True)
        self.pushButton_wlanlogin.setObjectName("pushButton_wlanlogin")
        self.horizontalLayout_7.addWidget(self.pushButton_wlanlogin)
        self.pushButton_wlanlogout = QtWidgets.QPushButton(self.page_2)
        self.pushButton_wlanlogout.setObjectName("pushButton_wlanlogout")
        self.horizontalLayout_7.addWidget(self.pushButton_wlanlogout)
        self.verticalLayout_3.addLayout(self.horizontalLayout_7)
        spacerItem8 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem8)
        self.verticalLayout_4.addLayout(self.verticalLayout_3)
        self.stackedWidget.addWidget(self.page_2)
        self.gridLayout.addWidget(self.stackedWidget, 7, 0, 2, 3)
        self.verticalLayout.addLayout(self.gridLayout)
        self.textBrowser_info = QtWidgets.QTextBrowser(Dialog)
        self.textBrowser_info.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.textBrowser_info.setMouseTracking(False)
        self.textBrowser_info.setTabletTracking(True)
        self.textBrowser_info.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.textBrowser_info.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.textBrowser_info.setStyleSheet("background-color: rgb(240, 240, 240);")
        self.textBrowser_info.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.textBrowser_info.setFrameShadow(QtWidgets.QFrame.Plain)
        self.textBrowser_info.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.textBrowser_info.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.textBrowser_info.setReadOnly(True)
        self.textBrowser_info.setObjectName("textBrowser_info")
        self.verticalLayout.addWidget(self.textBrowser_info)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.pushButton_help = QtWidgets.QPushButton(Dialog)
        self.pushButton_help.setMaximumSize(QtCore.QSize(20, 16777215))
        self.pushButton_help.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/Main/Media/help.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_help.setIcon(icon)
        self.pushButton_help.setIconSize(QtCore.QSize(20, 20))
        self.pushButton_help.setFlat(True)
        self.pushButton_help.setObjectName("pushButton_help")
        self.horizontalLayout_3.addWidget(self.pushButton_help)
        self.pushButton_about = QtWidgets.QPushButton(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_about.sizePolicy().hasHeightForWidth())
        self.pushButton_about.setSizePolicy(sizePolicy)
        self.pushButton_about.setMaximumSize(QtCore.QSize(20, 16777215))
        self.pushButton_about.setFocusPolicy(QtCore.Qt.NoFocus)
        self.pushButton_about.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/Main/Media/info.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_about.setIcon(icon1)
        self.pushButton_about.setIconSize(QtCore.QSize(20, 20))
        self.pushButton_about.setFlat(True)
        self.pushButton_about.setObjectName("pushButton_about")
        self.horizontalLayout_3.addWidget(self.pushButton_about)
        self.pushButton_more = QtWidgets.QPushButton(Dialog)
        self.pushButton_more.setObjectName("pushButton_more")
        self.horizontalLayout_3.addWidget(self.pushButton_more)
        self.pushButton_exit = QtWidgets.QPushButton(Dialog)
        self.pushButton_exit.setMaximumSize(QtCore.QSize(10000, 16777215))
        self.pushButton_exit.setFocusPolicy(QtCore.Qt.NoFocus)
        self.pushButton_exit.setIconSize(QtCore.QSize(16, 16))
        self.pushButton_exit.setFlat(False)
        self.pushButton_exit.setObjectName("pushButton_exit")
        self.horizontalLayout_3.addWidget(self.pushButton_exit)
        spacerItem9 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem9)
        self.pushButton_login = QtWidgets.QPushButton(Dialog)
        self.pushButton_login.setBaseSize(QtCore.QSize(0, 0))
        self.pushButton_login.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.pushButton_login.setDefault(True)
        self.pushButton_login.setObjectName("pushButton_login")
        self.horizontalLayout_3.addWidget(self.pushButton_login)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.label_user.setBuddy(self.lineEdit_user)
        self.label_passwd.setBuddy(self.lineEdit_passwd)

        self.retranslateUi(Dialog)
        self.stackedWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Dialog)
        Dialog.setTabOrder(self.lineEdit_user, self.lineEdit_passwd)
        Dialog.setTabOrder(self.lineEdit_passwd, self.radioButton_school)
        Dialog.setTabOrder(self.radioButton_school, self.radioButton_ct)
        Dialog.setTabOrder(self.radioButton_ct, self.radioButton_cu)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.radioButton_school.setText(_translate("Dialog", "校园有线/图书馆"))
        self.radioButton_wlan.setText(_translate("Dialog", "校园WLAN"))
        self.radioButton_ct.setText(_translate("Dialog", "电信"))
        self.radioButton_cmcc.setText(_translate("Dialog", "移动"))
        self.radioButton_cu.setText(_translate("Dialog", "联通"))
        self.label_user.setText(_translate("Dialog", "用户名(&U)"))
        self.label_logo.setText(_translate("Dialog", "华中师范大学校园网自动登录程序"))
        self.lineEdit_user.setPlaceholderText(_translate("Dialog", "请输入用户名，一般为学工号"))
        self.label_passwd.setText(_translate("Dialog", "密码(&P)"))
        self.lineEdit_passwd.setPlaceholderText(_translate("Dialog", "请输入校园网密码"))
        self.checkBox_keeppasswd.setText(_translate("Dialog", "保存密码到注册表"))
        self.checkBox_auth.setText(_translate("Dialog", "不显示界面直接登录（适用于开机自动认证）"))
        self.checkBox_server.setText(_translate("Dialog", "当连接失败时自动重试其他认证服务器"))
        self.pushButton_test.setText(_translate("Dialog", "测试本机到到Baidu首页的连接性"))
        self.pushButton_lanlogin.setText(_translate("Dialog", "  新认证服务器登录  "))
        self.pushButton_lanlogout.setText(_translate("Dialog", "注销"))
        self.pushButton_wlanlogin.setText(_translate("Dialog", "旧认证服务器登录"))
        self.pushButton_wlanlogout.setText(_translate("Dialog", "注销"))
        self.pushButton_more.setText(_translate("Dialog", "测试(&T)"))
        self.pushButton_exit.setText(_translate("Dialog", "退出(&E)"))
        self.pushButton_login.setText(_translate("Dialog", "登录(&L)"))

